# Generated by Django 5.1.4 on 2024-12-12 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title or summary of the notification.', max_length=255)),
                ('message', models.TextField(blank=True, help_text='Optional detailed message of the notification.', null=True)),
                ('notification_type', models.CharField(choices=[('INFO', 'Information'), ('ALERT', 'Alert'), ('MESSAGE', 'Message')], default='INFO', help_text='Type of notification (e.g., Information, Alert, etc.).', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the notification was created.')),
                ('is_read', models.BooleanField(default=False, help_text='Flag to indicate if the notification has been read.')),
                ('link', models.URLField(blank=True, help_text='Optional link for more details or action.', null=True)),
                ('user', models.ForeignKey(help_text='The user to whom the notification belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
