# Generated by Django 5.1.4 on 2024-12-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theatre_and_Seats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='row',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
