# Generated by Django 5.1.4 on 2024-12-17 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theatre_and_Seats', '0002_seat_row'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='show_end_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='show_start_time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Theatre_and_Seats.seat'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='theatre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Theatre_and_Seats.theatre'),
        ),
    ]
