# Generated by Django 5.1.4 on 2024-12-17 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Theatre_and_Seats', '0003_rename_show_end_time_schedule_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theatre',
            old_name='theatre_name',
            new_name='theatre',
        ),
    ]
