# Generated by Django 5.1.4 on 2024-12-17 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Theatre_and_Seats', '0004_rename_theatre_name_theatre_theatre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theatre',
            old_name='theatre',
            new_name='theatre_name',
        ),
    ]
