# Generated by Django 5.1.4 on 2024-12-18 18:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theatre_and_Seats', '0006_alter_theatre_theatre_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='seat_catagory',
        ),
        migrations.AlterField(
            model_name='seat',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='theatre',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
