# Generated by Django 5.1.4 on 2024-12-10 13:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=220, null=True)),
                ('description', models.TextField()),
                ('run_time', models.TimeField()),
                ('production_home', models.CharField(blank=True, max_length=220, null=True)),
                ('release_date', models.DateTimeField()),
                ('imdb_rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rotten_tomato', models.CharField(blank=True, max_length=20, null=True)),
                ('Director', models.CharField(blank=True, max_length=220, null=True)),
                ('genre', models.CharField(choices=[('ACTION', 'Action'), ('FANTASY', 'Fantasy'), ('SCIENCE FICTION', 'Science Fiction'), ('ROMANCE', 'Romance'), ('DOCUMENTRY', 'Documentry'), ('DRAMA', 'Drama'), ('ANIME', 'ANIME'), ('ANIMATION', 'Animation'), ('MYSTERY', 'Mystery'), ('HORROR', 'Horror'), ('THRILLER', 'Thriller'), ('WESTERN', 'Westerm'), ('WAR', 'War'), ('SPORTS', 'Sports'), ('Biography', 'Biography')], max_length=30)),
                ('expiration', models.DateTimeField()),
                ('actor', models.CharField(blank=True, max_length=100, null=True)),
                ('actress', models.CharField(blank=True, max_length=100, null=True)),
                ('movie_type', models.CharField(choices=[('G', 'General Audiences'), ('PG', 'Parental Guidance Suggested'), ('PG-13', 'Parents Strongly Cautioned'), ('R', 'Restricted'), ('NC-17', 'Adults Only')], max_length=30)),
            ],
        ),
    ]
