# Generated by Django 5.1.4 on 2024-12-10 13:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Theatre_and_Seats', '0001_initial'),
        ('movie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ticket_serial_no', models.CharField(blank=True, max_length=30, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Theatre_and_Seats.schedule')),
                ('seat_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Theatre_and_Seats.seat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
