# Generated by Django 5.1.4 on 2024-12-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_options_remove_ticket_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='theatre',
            new_name='theatre_name',
        ),
    ]
