# Generated by Django 5.1.4 on 2024-12-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_rename_theatre_ticket_theatre_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='theatre_name',
            new_name='theatre',
        ),
    ]
