# Generated by Django 5.1.4 on 2024-12-12 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theatre_and_Seats', '0001_initial'),
        ('tickets', '0005_remove_ticket_theatre_ticket_theatre_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={},
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='theatre_name',
            new_name='theatre',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='is_avialable',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_serial_no',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Theatre_and_Seats.seat'),
        ),
    ]
