# Generated by Django 5.1.4 on 2024-12-17 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theatre_and_Seats', '0003_rename_show_end_time_schedule_end_time_and_more'),
        ('tickets', '0007_ticket_created_at_ticket_purchased_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Theatre_and_Seats.schedule'),
        ),
    ]
