# Generated by Django 5.1.4 on 2024-12-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticket_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='created_by',
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_bought',
            field=models.BooleanField(default=False),
        ),
    ]
