# Generated by Django 5.1.4 on 2024-12-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_rename_logs_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='timestampe',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
