# Generated by Django 5.1.4 on 2025-01-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_log_timestampe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='timestampe',
        ),
        migrations.RemoveField(
            model_name='log',
            name='user',
        ),
        migrations.AddField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
